name: Build Eleventy

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm run rebuild

      - name: Deploy to github pages
        if: ${{ true }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ../html
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push
        if: ${{ true }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated 11ty build
